name: "Kotlint"
description: "Run ktlint in your repository"
inputs:
  patterns:
    description: "A list of patterns to pass along to the ktlint command"
    required: false
    default: "**/*.kt"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.patterns }}
branding:
  icon: eye
  color: purple
